/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    utilisateurs: UtilisateurAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    produits: Produit;
    'categories-produits': CategoriesProduit;
    temoignages: Temoignage;
    faq: Faq;
    media: Media;
    utilisateurs: Utilisateur;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    produits: ProduitsSelect<false> | ProduitsSelect<true>;
    'categories-produits': CategoriesProduitsSelect<false> | CategoriesProduitsSelect<true>;
    temoignages: TemoignagesSelect<false> | TemoignagesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    utilisateurs: UtilisateursSelect<false> | UtilisateursSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'fr' | 'fr'[];
  globals: {
    etablissement: Etablissement;
    navigation: Navigation;
    'reglages-seo': ReglagesSeo;
  };
  globalsSelect: {
    etablissement: EtablissementSelect<false> | EtablissementSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'reglages-seo': ReglagesSeoSelect<false> | ReglagesSeoSelect<true>;
  };
  locale: 'fr';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Utilisateur;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UtilisateurAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * La page dont le slug est « accueil » est servie a la racine du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  titre: string;
  /**
   * Partie de l'adresse qui identifie la page. Genere automatiquement, modifiable. Attention : le changer casse les liens existants.
   */
  slug: string;
  /**
   * Empilez les blocs pour composer la page. Ils se reordonnent par glisser-deposer.
   */
  contenu?:
    | (
        | BlocHero
        | BlocTexteImage
        | BlocProduits
        | BlocGalerie
        | BlocHoraires
        | BlocTemoignages
        | BlocFaq
        | BlocContact
        | BlocCta
      )[]
    | null;
  seo?: MetaSeo;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocHero".
 */
export interface BlocHero {
  variante: 'couverture' | 'lateral' | 'texte';
  /**
   * Titre principal de la page (h1). Un seul par page.
   */
  titre: string;
  sousTitre?: string | null;
  /**
   * Format paysage recommande, au moins 1600 px de large.
   */
  image?: (number | null) | Media;
  alignement?: ('gauche' | 'centre') | null;
  /**
   * Necessaire pour garder le texte lisible sur une photo claire.
   */
  opaciteVoile?: number | null;
  boutons?:
    | {
        type?: ('interne' | 'externe' | 'telephone' | 'email' | 'ancre') | null;
        style?: ('primaire' | 'secondaire' | 'discret') | null;
        libelle: string;
        reference?: (number | null) | Page;
        url?: string | null;
        /**
         * Laisser vide pour reprendre le numero de la fiche Etablissement.
         */
        telephone?: string | null;
        /**
         * Laisser vide pour reprendre l'e-mail de la fiche Etablissement.
         */
        email?: string | null;
        /**
         * Identifiant defini dans l'apparence d'un bloc, sans le #.
         */
        ancre?: string | null;
        nouvelOnglet?: boolean | null;
        id?: string | null;
      }[]
    | null;
  apparence?: ApparenceBloc;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Lue par les lecteurs d'ecran et affichee si l'image ne charge pas. Decrivez ce que l'on voit, sans commencer par « photo de ».
   */
  alt: string;
  /**
   * Facultative, affichee sous l image dans les galeries.
   */
  legende?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    vignette?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    carte?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banniere?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Reglages de fond, d espacement et d ancrage de ce bloc.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ApparenceBloc".
 */
export interface ApparenceBloc {
  fond?: ('defaut' | 'attenue' | 'primaire') | null;
  espacement?: ('compact' | 'normal' | 'large') | null;
  /**
   * Permet de pointer un lien vers ce bloc. Ex. : horaires.
   */
  ancre?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocTexteImage".
 */
export interface BlocTexteImage {
  /**
   * Sur mobile, l image passe toujours au-dessus du texte.
   */
  positionImage?: ('gauche' | 'droite') | null;
  formatImage?: ('paysage' | 'carre' | 'portrait') | null;
  image: number | Media;
  titre?: string | null;
  texte?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  boutons?:
    | {
        type?: ('interne' | 'externe' | 'telephone' | 'email' | 'ancre') | null;
        style?: ('primaire' | 'secondaire' | 'discret') | null;
        libelle: string;
        reference?: (number | null) | Page;
        url?: string | null;
        /**
         * Laisser vide pour reprendre le numero de la fiche Etablissement.
         */
        telephone?: string | null;
        /**
         * Laisser vide pour reprendre l'e-mail de la fiche Etablissement.
         */
        email?: string | null;
        /**
         * Identifiant defini dans l'apparence d'un bloc, sans le #.
         */
        ancre?: string | null;
        nouvelOnglet?: boolean | null;
        id?: string | null;
      }[]
    | null;
  apparence?: ApparenceBloc;
  id?: string | null;
  blockName?: string | null;
  blockType: 'texteImage';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocProduits".
 */
export interface BlocProduits {
  titre?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * « Mis en avant » suit la case cochee sur chaque produit : la page d'accueil se met a jour toute seule.
   */
  mode: 'misesEnAvant' | 'categorie' | 'selection' | 'tous';
  categorie?: (number | null) | CategoriesProduit;
  /**
   * L ordre choisi ici est celui de l affichage.
   */
  selection?: (number | Produit)[] | null;
  limite?: number | null;
  colonnes?: ('2' | '3' | '4') | null;
  afficherPrix?: boolean | null;
  afficherLienVoirTout?: boolean | null;
  apparence?: ApparenceBloc;
  id?: string | null;
  blockName?: string | null;
  blockType: 'produits';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories-produits".
 */
export interface CategoriesProduit {
  id: number;
  nom: string;
  /**
   * Partie de l'adresse qui identifie la page. Genere automatiquement, modifiable. Attention : le changer casse les liens existants.
   */
  slug: string;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produits".
 */
export interface Produit {
  id: number;
  nom: string;
  /**
   * Partie de l'adresse qui identifie la page. Genere automatiquement, modifiable. Attention : le changer casse les liens existants.
   */
  slug: string;
  /**
   * Apparait dans les blocs « produits mis en avant », notamment sur la page d'accueil.
   */
  miseEnAvant?: boolean | null;
  /**
   * Les petits nombres passent en premier.
   */
  ordre?: number | null;
  imagePrincipale: number | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Texte libre : le site ne vend rien, il informe.
   */
  prixIndicatif?: string | null;
  disponibilite?: ('permanent' | 'saisonnier' | 'surCommande') | null;
  categorie?: (number | null) | CategoriesProduit;
  /**
   * Affiches sur la fiche produit. L'information reglementaire complete reste due en boutique.
   */
  allergenes?:
    | (
        | 'gluten'
        | 'oeufs'
        | 'lait'
        | 'fruits-a-coque'
        | 'arachides'
        | 'soja'
        | 'sesame'
        | 'sulfites'
        | 'lupin'
        | 'moutarde'
        | 'celeri'
        | 'poisson'
        | 'crustaces'
        | 'mollusques'
      )[]
    | null;
  galerie?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  seo?: MetaSeo;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetaSeo".
 */
export interface MetaSeo {
  /**
   * Vise 50 a 60 caracteres. Vide, le titre du document est repris et le suffixe du site ajoute.
   */
  titre?: string | null;
  /**
   * Vise 120 a 160 caracteres. Vide, la description globale du site est reprise.
   */
  description?: string | null;
  /**
   * Utilisee par Facebook, WhatsApp et LinkedIn. Format ideal 1200 x 630 px. Vide, l'image par defaut du site est reprise.
   */
  image?: (number | null) | Media;
  /**
   * La page reste accessible par son adresse mais sort du sitemap et des resultats.
   */
  noindex?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocGalerie".
 */
export interface BlocGalerie {
  titre?: string | null;
  images: {
    image: number | Media;
    legende?: string | null;
    id?: string | null;
  }[];
  /**
   * Le mobile affiche toujours une seule colonne.
   */
  colonnes?: ('2' | '3' | '4') | null;
  format?: ('carre' | 'portrait' | 'paysage' | 'naturel') | null;
  /**
   * Ajoute un petit script a la page. A laisser decoche si les images n ont pas besoin d etre vues en grand.
   */
  agrandissement?: boolean | null;
  apparence?: ApparenceBloc;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galerie';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocHoraires".
 */
export interface BlocHoraires {
  /**
   * Vide, le titre « Horaires d'ouverture » est utilise.
   */
  titre?: string | null;
  /**
   * Garder la fiche Etablissement evite d'avoir a mettre a jour les horaires a deux endroits.
   */
  source?: ('etablissement' | 'personnalise') | null;
  /**
   * Un jour absent de cette liste est considere comme ferme.
   */
  horairesPersonnalises?:
    | {
        jour: 'lundi' | 'mardi' | 'mercredi' | 'jeudi' | 'vendredi' | 'samedi' | 'dimanche';
        ferme?: boolean | null;
        /**
         * Ajoutez un second creneau pour une coupure a midi.
         */
        creneaux?:
          | {
              ouvre?: string | null;
              ferme?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  afficherFermetures?: boolean | null;
  note?: string | null;
  apparence?: ApparenceBloc;
  id?: string | null;
  blockName?: string | null;
  blockType: 'horaires';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocTemoignages".
 */
export interface BlocTemoignages {
  titre?: string | null;
  mode?: ('recents' | 'selection') | null;
  limite?: number | null;
  selection?: (number | Temoignage)[] | null;
  afficherNotes?: boolean | null;
  apparence?: ApparenceBloc;
  id?: string | null;
  blockName?: string | null;
  blockType: 'temoignages';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages".
 */
export interface Temoignage {
  id: number;
  /**
   * Prenom et initiale suffisent : « Marie L. ».
   */
  auteur: string;
  texte: string;
  note?: number | null;
  date?: string | null;
  source?: ('boutique' | 'google' | 'reseaux') | null;
  visible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocFaq".
 */
export interface BlocFaq {
  titre?: string | null;
  mode?: ('toutes' | 'selection') | null;
  selection?: (number | Faq)[] | null;
  /**
   * Permet a Google d'afficher les questions directement dans ses resultats. A n'activer qu'une fois par page.
   */
  genererJsonLd?: boolean | null;
  apparence?: ApparenceBloc;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  reponse: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Les petits nombres passent en premier.
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocContact".
 */
export interface BlocContact {
  titre?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  afficherCoordonnees?: boolean | null;
  afficherHoraires?: boolean | null;
  afficherReseaux?: boolean | null;
  afficherCarte?: boolean | null;
  /**
   * Capture de la carte, cliquable vers l'itineraire. Une image evite la carte interactive, lourde et bourree de traceurs.
   */
  imageCarte?: (number | null) | Media;
  apparence?: ApparenceBloc;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocCta".
 */
export interface BlocCta {
  titre: string;
  texte?: string | null;
  boutons?:
    | {
        type?: ('interne' | 'externe' | 'telephone' | 'email' | 'ancre') | null;
        style?: ('primaire' | 'secondaire' | 'discret') | null;
        libelle: string;
        reference?: (number | null) | Page;
        url?: string | null;
        /**
         * Laisser vide pour reprendre le numero de la fiche Etablissement.
         */
        telephone?: string | null;
        /**
         * Laisser vide pour reprendre l'e-mail de la fiche Etablissement.
         */
        email?: string | null;
        /**
         * Identifiant defini dans l'apparence d'un bloc, sans le #.
         */
        ancre?: string | null;
        nouvelOnglet?: boolean | null;
        id?: string | null;
      }[]
    | null;
  apparence?: ApparenceBloc;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utilisateurs".
 */
export interface Utilisateur {
  id: number;
  nom: string;
  /**
   * L'editeur gere le contenu ; l'administrateur gere aussi les comptes.
   */
  role: 'administrateur' | 'editeur';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'utilisateurs';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'produits';
        value: number | Produit;
      } | null)
    | ({
        relationTo: 'categories-produits';
        value: number | CategoriesProduit;
      } | null)
    | ({
        relationTo: 'temoignages';
        value: number | Temoignage;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'utilisateurs';
        value: number | Utilisateur;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'utilisateurs';
    value: number | Utilisateur;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'utilisateurs';
    value: number | Utilisateur;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  contenu?:
    | T
    | {
        hero?: T | BlocHeroSelect<T>;
        texteImage?: T | BlocTexteImageSelect<T>;
        produits?: T | BlocProduitsSelect<T>;
        galerie?: T | BlocGalerieSelect<T>;
        horaires?: T | BlocHorairesSelect<T>;
        temoignages?: T | BlocTemoignagesSelect<T>;
        faq?: T | BlocFaqSelect<T>;
        contact?: T | BlocContactSelect<T>;
        cta?: T | BlocCtaSelect<T>;
      };
  seo?: T | MetaSeoSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocHero_select".
 */
export interface BlocHeroSelect<T extends boolean = true> {
  variante?: T;
  titre?: T;
  sousTitre?: T;
  image?: T;
  alignement?: T;
  opaciteVoile?: T;
  boutons?:
    | T
    | {
        type?: T;
        style?: T;
        libelle?: T;
        reference?: T;
        url?: T;
        telephone?: T;
        email?: T;
        ancre?: T;
        nouvelOnglet?: T;
        id?: T;
      };
  apparence?: T | ApparenceBlocSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ApparenceBloc_select".
 */
export interface ApparenceBlocSelect<T extends boolean = true> {
  fond?: T;
  espacement?: T;
  ancre?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocTexteImage_select".
 */
export interface BlocTexteImageSelect<T extends boolean = true> {
  positionImage?: T;
  formatImage?: T;
  image?: T;
  titre?: T;
  texte?: T;
  boutons?:
    | T
    | {
        type?: T;
        style?: T;
        libelle?: T;
        reference?: T;
        url?: T;
        telephone?: T;
        email?: T;
        ancre?: T;
        nouvelOnglet?: T;
        id?: T;
      };
  apparence?: T | ApparenceBlocSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocProduits_select".
 */
export interface BlocProduitsSelect<T extends boolean = true> {
  titre?: T;
  intro?: T;
  mode?: T;
  categorie?: T;
  selection?: T;
  limite?: T;
  colonnes?: T;
  afficherPrix?: T;
  afficherLienVoirTout?: T;
  apparence?: T | ApparenceBlocSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocGalerie_select".
 */
export interface BlocGalerieSelect<T extends boolean = true> {
  titre?: T;
  images?:
    | T
    | {
        image?: T;
        legende?: T;
        id?: T;
      };
  colonnes?: T;
  format?: T;
  agrandissement?: T;
  apparence?: T | ApparenceBlocSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocHoraires_select".
 */
export interface BlocHorairesSelect<T extends boolean = true> {
  titre?: T;
  source?: T;
  horairesPersonnalises?:
    | T
    | {
        jour?: T;
        ferme?: T;
        creneaux?:
          | T
          | {
              ouvre?: T;
              ferme?: T;
              id?: T;
            };
        id?: T;
      };
  afficherFermetures?: T;
  note?: T;
  apparence?: T | ApparenceBlocSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocTemoignages_select".
 */
export interface BlocTemoignagesSelect<T extends boolean = true> {
  titre?: T;
  mode?: T;
  limite?: T;
  selection?: T;
  afficherNotes?: T;
  apparence?: T | ApparenceBlocSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocFaq_select".
 */
export interface BlocFaqSelect<T extends boolean = true> {
  titre?: T;
  mode?: T;
  selection?: T;
  genererJsonLd?: T;
  apparence?: T | ApparenceBlocSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocContact_select".
 */
export interface BlocContactSelect<T extends boolean = true> {
  titre?: T;
  intro?: T;
  afficherCoordonnees?: T;
  afficherHoraires?: T;
  afficherReseaux?: T;
  afficherCarte?: T;
  imageCarte?: T;
  apparence?: T | ApparenceBlocSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlocCta_select".
 */
export interface BlocCtaSelect<T extends boolean = true> {
  titre?: T;
  texte?: T;
  boutons?:
    | T
    | {
        type?: T;
        style?: T;
        libelle?: T;
        reference?: T;
        url?: T;
        telephone?: T;
        email?: T;
        ancre?: T;
        nouvelOnglet?: T;
        id?: T;
      };
  apparence?: T | ApparenceBlocSelect<T>;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MetaSeo_select".
 */
export interface MetaSeoSelect<T extends boolean = true> {
  titre?: T;
  description?: T;
  image?: T;
  noindex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produits_select".
 */
export interface ProduitsSelect<T extends boolean = true> {
  nom?: T;
  slug?: T;
  miseEnAvant?: T;
  ordre?: T;
  imagePrincipale?: T;
  description?: T;
  prixIndicatif?: T;
  disponibilite?: T;
  categorie?: T;
  allergenes?: T;
  galerie?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seo?: T | MetaSeoSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories-produits_select".
 */
export interface CategoriesProduitsSelect<T extends boolean = true> {
  nom?: T;
  slug?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temoignages_select".
 */
export interface TemoignagesSelect<T extends boolean = true> {
  auteur?: T;
  texte?: T;
  note?: T;
  date?: T;
  source?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  reponse?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  legende?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        vignette?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        carte?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banniere?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "utilisateurs_select".
 */
export interface UtilisateursSelect<T extends boolean = true> {
  nom?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Coordonnees et horaires du commerce, repris partout sur le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etablissement".
 */
export interface Etablissement {
  id: number;
  nom: string;
  /**
   * Determine la categorie transmise a Google.
   */
  typeCommerce: 'boulangerie' | 'patisserie' | 'fleuriste' | 'boucherie' | 'epicerie' | 'cafe' | 'restaurant' | 'autre';
  slogan?: string | null;
  /**
   * Deux ou trois phrases. Reprise dans les donnees structurees et comme description par defaut.
   */
  description?: string | null;
  logo?: (number | null) | Media;
  telephone?: string | null;
  email?: string | null;
  adresse?: Adresse;
  geo?: CoordonneesGeo;
  /**
   * Lien Google Maps ou Apple Plans utilise par le bouton « Obtenir l'itineraire ».
   */
  lienItineraire?: string | null;
  accessibilitePmr?: boolean | null;
  moyensPaiement?: string | null;
  /**
   * Un jour absent de cette liste est considere comme ferme.
   */
  horaires?:
    | {
        jour: 'lundi' | 'mardi' | 'mercredi' | 'jeudi' | 'vendredi' | 'samedi' | 'dimanche';
        ferme?: boolean | null;
        /**
         * Ajoutez un second creneau pour une coupure a midi.
         */
        creneaux?:
          | {
              ouvre?: string | null;
              ferme?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Signalees sur le site et transmises a Google. Les periodes passees sont ignorees automatiquement.
   */
  fermeturesExceptionnelles?:
    | {
        du: string;
        au: string;
        motif?: string | null;
        id?: string | null;
      }[]
    | null;
  reseauxSociaux?:
    | {
        plateforme: 'facebook' | 'instagram' | 'tiktok' | 'linkedin' | 'youtube' | 'google' | 'autre';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Adresse".
 */
export interface Adresse {
  rue?: string | null;
  complement?: string | null;
  codePostal?: string | null;
  ville?: string | null;
  pays?: string | null;
}
/**
 * Facultatif mais recommande : aide Google a placer le commerce sur la carte. Se releve dans Google Maps par un clic droit sur la boutique.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoordonneesGeo".
 */
export interface CoordonneesGeo {
  latitude?: number | null;
  longitude?: number | null;
}
/**
 * Menus de l'en-tete et du pied de page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Au-dela de six entrees, le menu devient difficile a lire sur mobile.
   */
  menuPrincipal?:
    | {
        type?: ('interne' | 'externe' | 'telephone' | 'email' | 'ancre') | null;
        libelle: string;
        reference?: (number | null) | Page;
        url?: string | null;
        /**
         * Laisser vide pour reprendre le numero de la fiche Etablissement.
         */
        telephone?: string | null;
        /**
         * Laisser vide pour reprendre l'e-mail de la fiche Etablissement.
         */
        email?: string | null;
        /**
         * Identifiant defini dans l'apparence d'un bloc, sans le #.
         */
        ancre?: string | null;
        nouvelOnglet?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaEnTete?: {
    actif?: boolean | null;
    lien?: Lien;
  };
  menuPied?:
    | {
        type?: ('interne' | 'externe' | 'telephone' | 'email' | 'ancre') | null;
        libelle: string;
        reference?: (number | null) | Page;
        url?: string | null;
        /**
         * Laisser vide pour reprendre le numero de la fiche Etablissement.
         */
        telephone?: string | null;
        /**
         * Laisser vide pour reprendre l'e-mail de la fiche Etablissement.
         */
        email?: string | null;
        /**
         * Identifiant defini dans l'apparence d'un bloc, sans le #.
         */
        ancre?: string | null;
        nouvelOnglet?: boolean | null;
        id?: string | null;
      }[]
    | null;
  mentionPied?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Lien".
 */
export interface Lien {
  type?: ('interne' | 'externe' | 'telephone' | 'email' | 'ancre') | null;
  style?: ('primaire' | 'secondaire' | 'discret') | null;
  libelle: string;
  reference?: (number | null) | Page;
  url?: string | null;
  /**
   * Laisser vide pour reprendre le numero de la fiche Etablissement.
   */
  telephone?: string | null;
  /**
   * Laisser vide pour reprendre l'e-mail de la fiche Etablissement.
   */
  email?: string | null;
  /**
   * Identifiant defini dans l'apparence d'un bloc, sans le #.
   */
  ancre?: string | null;
  nouvelOnglet?: boolean | null;
}
/**
 * Valeurs par defaut utilisees quand une page ne definit pas les siennes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-seo".
 */
export interface ReglagesSeo {
  id: number;
  /**
   * Ajoute apres le titre de chaque page, separe par un tiret. Ex. : « Boulangerie Martin, Lyon 3e ».
   */
  suffixeTitre?: string | null;
  descriptionParDefaut?: string | null;
  /**
   * Format ideal 1200 x 630 px.
   */
  imagePartage?: (number | null) | Media;
  /**
   * A cocher le jour de la mise en ligne. Decoche, le site entier est masque des moteurs : c'est le reglage a garder pendant la phase de preparation.
   */
  autoriserIndexation?: boolean | null;
  /**
   * Contenu de l'attribut content de la balise fournie par Google.
   */
  verificationGoogle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etablissement_select".
 */
export interface EtablissementSelect<T extends boolean = true> {
  nom?: T;
  typeCommerce?: T;
  slogan?: T;
  description?: T;
  logo?: T;
  telephone?: T;
  email?: T;
  adresse?: T | AdresseSelect<T>;
  geo?: T | CoordonneesGeoSelect<T>;
  lienItineraire?: T;
  accessibilitePmr?: T;
  moyensPaiement?: T;
  horaires?:
    | T
    | {
        jour?: T;
        ferme?: T;
        creneaux?:
          | T
          | {
              ouvre?: T;
              ferme?: T;
              id?: T;
            };
        id?: T;
      };
  fermeturesExceptionnelles?:
    | T
    | {
        du?: T;
        au?: T;
        motif?: T;
        id?: T;
      };
  reseauxSociaux?:
    | T
    | {
        plateforme?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Adresse_select".
 */
export interface AdresseSelect<T extends boolean = true> {
  rue?: T;
  complement?: T;
  codePostal?: T;
  ville?: T;
  pays?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CoordonneesGeo_select".
 */
export interface CoordonneesGeoSelect<T extends boolean = true> {
  latitude?: T;
  longitude?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  menuPrincipal?:
    | T
    | {
        type?: T;
        libelle?: T;
        reference?: T;
        url?: T;
        telephone?: T;
        email?: T;
        ancre?: T;
        nouvelOnglet?: T;
        id?: T;
      };
  ctaEnTete?:
    | T
    | {
        actif?: T;
        lien?: T | LienSelect<T>;
      };
  menuPied?:
    | T
    | {
        type?: T;
        libelle?: T;
        reference?: T;
        url?: T;
        telephone?: T;
        email?: T;
        ancre?: T;
        nouvelOnglet?: T;
        id?: T;
      };
  mentionPied?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Lien_select".
 */
export interface LienSelect<T extends boolean = true> {
  type?: T;
  style?: T;
  libelle?: T;
  reference?: T;
  url?: T;
  telephone?: T;
  email?: T;
  ancre?: T;
  nouvelOnglet?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reglages-seo_select".
 */
export interface ReglagesSeoSelect<T extends boolean = true> {
  suffixeTitre?: T;
  descriptionParDefaut?: T;
  imagePartage?: T;
  autoriserIndexation?: T;
  verificationGoogle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'produits';
          value: number | Produit;
        } | null);
    global?: string | null;
    user?: (number | null) | Utilisateur;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}